
services:
  backend:
    build: .
    container_name: kubetask-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/kubetask
      # - JWT_SECRET=supersecretkey
    depends_on:
      - mongo

  mongo:
    image: mongo:8.0.13
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
